blank_issues_enabled: false
contact_links:
  - name: 🔒 Report a vulnerability
    url: https://github.com/lucasvmigotto/rusteams/blob/dev/SECURITY.md
    about: Do NOT open public issues for token leaks or injections
